import React from 'react';
import {
  Box, Flex, Heading, Text, Button, VStack, HStack, Image, Icon, Divider, SimpleGrid, Avatar, Accordion, AccordionItem, AccordionButton, AccordionPanel, AccordionIcon, useColorModeValue, Stack, Link
} from '@chakra-ui/react';
import { FaRocket, FaCheckCircle, FaPlay, FaBrain, FaMagic, FaUserShield, FaClock, FaTree, FaStar, FaLock, FaUserTie } from 'react-icons/fa';

const testimonials = [
  {
    name: 'Sarah K.',
    role: 'Marketing Manager',
    quote: 'CandidateV is a game-changer! I landed three interviews in my first week using it. The tailored CVs make a huge difference.',
    avatar: '',
    rating: 5,
  },
  {
    name: 'James T.',
    role: 'Software Engineer',
    quote: 'I used to spend hours on every application. Now it takes minutes and I get more callbacks.',
    avatar: '',
    rating: 5,
  },
  {
    name: 'Priya S.',
    role: 'Recent Grad',
    quote: 'The Career Arc keeps all my experience organized. I feel so much more confident applying!',
    avatar: '',
    rating: 5,
  },
];

const faqs = [
  {
    q: 'How does the Career Arc™ work?',
    a: 'Your Career Arc™ is your private, intelligent career repository. Upload your CVs or add experiences, and our AI structures and stores your data for future applications.'
  },
  {
    q: 'Is my data secure with CandidateV?',
    a: 'Absolutely. Your data is encrypted and never shared. You have full control over your Career Arc™.'
  },
  {
    q: 'What kind of CV formats can I upload?',
    a: 'We support PDF, DOC, and DOCX formats.'
  },
  {
    q: 'How does the AI tailor my CV and cover letter?',
    a: 'Our AI analyzes your Arc and the job description to generate optimized, personalized documents for each application.'
  },
  {
    q: 'Can I edit the documents generated by CandidateV?',
    a: 'Yes! You can review and edit any generated CV or cover letter before downloading.'
  },
  {
    q: 'What if I want to cancel my subscription?',
    a: 'You can cancel anytime from your account dashboard. No questions asked.'
  },
];

const plans = [
  {
    name: 'Career Starter',
    price: 'Free',
    features: [
      'Build your Career Arc™',
      'Basic CV parsing',
      '1 tailored application per month',
      'Email support',
    ],
    highlight: false,
  },
  {
    name: 'Career Accelerator',
    price: '£14.99/mo',
    features: [
      'Unlimited tailored applications',
      'Advanced AI optimization',
      'Priority support',
      'Access to Application Wizard',
    ],
    highlight: true,
  },
  {
    name: 'Career Dominator',
    price: '£29.99/mo',
    features: [
      'Everything in Accelerator',
      '1:1 expert review',
      'Early access to new features',
      'Personalized job search insights',
    ],
    highlight: false,
  },
];

const HighConvertingLanding: React.FC = () => {
  const bg = 'lilac'; // theme color
  const cardBg = 'white';
  const accent = 'brand.400';
  return (
    <Box bg={bg} minH="100vh">
      {/* 1. Hero Section (no nav) */}
      <Flex direction={{ base: 'column', md: 'row' }} align="center" justify="space-between" px={{ base: 2, sm: 4, md: 16 }} py={{ base: 8, md: 16 }} bg="white">
        <VStack align="start" spacing={6} maxW={{ base: '100%', md: 'lg' }} w="100%">
          <Heading as="h1" textStyle="h1" fontSize={{ base: '2xl', sm: '3xl', md: '5xl' }} fontWeight="bold" color="navy">
            Stop Rewriting, Start Applying: Land Your Dream Job Faster with CandidateV.
          </Heading>
          <Text fontSize={{ base: 'md', md: 'xl' }} color="slate">
            Tired of endless CV tweaks for every job? CandidateV's AI uses your unique career history—your personal Career Arc™—to craft perfectly tailored CVs and cover letters in minutes, so you get noticed by employers.
          </Text>
          <HStack spacing={4} flexWrap="wrap">
            <Button colorScheme="brand" variant="solid" size={{ base: 'md', md: 'lg' }} borderRadius="md" leftIcon={<FaRocket />}>Create Your Free Account</Button>
            <Button colorScheme="brand" variant="outline" size={{ base: 'md', md: 'lg' }} borderRadius="md" leftIcon={<FaPlay />}>See How It Works (60s Video)</Button>
          </HStack>
          <Text fontSize={{ base: 'xs', md: 'sm' }} color="text.placeholder" mt={2}>
            Join 10,000+ job seekers already optimizing their applications!
          </Text>
        </VStack>
        <Box flex={1} display="flex" justifyContent="center" alignItems="center" mt={{ base: 10, md: 0 }} w="100%">
          <Image src="/hero-placeholder.png" alt="Hero Visual" boxSize={{ base: '220px', sm: '300px', md: '400px' }} objectFit="contain" borderRadius="lg" boxShadow="lg" />
        </Box>
      </Flex>

      {/* 2. Social Proof / As Seen On */}
      <Box w="full" py={4} bg="brand.50">
        <HStack justify="center" spacing={{ base: 4, md: 8 }} flexWrap="wrap">
          <Text color="slate" fontSize={{ base: 'xs', md: 'md' }}>As seen on</Text>
          <Image src="/logo1-placeholder.png" alt="Logo 1" boxSize={{ base: '36px', md: '60px' }} />
          <Image src="/logo2-placeholder.png" alt="Logo 2" boxSize={{ base: '36px', md: '60px' }} />
          <Image src="/logo3-placeholder.png" alt="Logo 3" boxSize={{ base: '36px', md: '60px' }} />
        </HStack>
      </Box>

      {/* 3. Problem / Solution Section */}
      <Box py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }} textAlign="center">
        <Heading as="h2" textStyle="h2" fontSize={{ base: 'xl', md: '2xl', lg: '4xl' }} mb={4} color="navy">The Job Application Grind is Real. CandidateV is Your Way Out.</Heading>
        <Text fontSize={{ base: 'md', md: 'lg' }} color="slate" maxW="2xl" mx="auto">
          Spending hours tailoring your CV for each role? Worried your application will get lost in the ATS black hole? Juggling multiple CV versions? It's exhausting and inefficient. CandidateV automates the tedious parts, so you can focus on what matters: acing the interview.
        </Text>
      </Box>

      {/* 4. Core Features & Benefits */}
      <Box id="features" py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }}>
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">Meet Your AI-Powered Application Toolkit</Heading>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={{ base: 6, md: 10 }}>
          <VStack align="start" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaBrain} boxSize={10} color={accent} />
            <Heading as="h3" size="md" color="navy">Build Once, Apply Perfectly, Forever.</Heading>
            <Text color="slate">Your Career Arc™ is your private, intelligent career repository. Simply upload your existing CVs or add your experiences. Arc™ extracts, structures, and uniquely stores every skill, achievement, and role. It's your living career story, constantly learning and ready to power your next application.</Text>
            <VStack align="start" spacing={1} fontSize="sm">
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Consolidate your entire career history in one smart place.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Ensure consistency and accuracy across all applications.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Your Arc™ gets more powerful with every update and application.</Text></HStack>
            </VStack>
          </VStack>
          <VStack align="start" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaMagic} boxSize={10} color={accent} />
            <Heading as="h3" size="md" color="navy">Tailored CVs & Cover Letters, Instantly.</Heading>
            <Text color="slate">Paste any job description, and let the Application Wizard work its magic. Leveraging your Career Arc™, our AI instantly analyzes the role, identifies key requirements, and generates a perfectly optimized CV and compelling cover letter. Say goodbye to generic applications.</Text>
            <VStack align="start" spacing={1} fontSize="sm">
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Beat Applicant Tracking Systems (ATS) with keyword optimization.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Highlight your most relevant experiences for each specific role.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Save hours per application, apply to more jobs, faster.</Text></HStack>
            </VStack>
          </VStack>
          <VStack align="start" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaTree} boxSize={10} color={accent} />
            <Heading as="h3" size="md" color="navy">Your Master Career Profile, Always Ready.</Heading>
            <Text color="slate">The Mega CV draws from your Arc™ to create a comprehensive master version of your resume, perfect for networking, speculative applications, or when you need a complete overview of your career journey. Adaptable and always up-to-date.</Text>
            <VStack align="start" spacing={1} fontSize="sm">
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>A complete, always-current master document.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Ideal for diverse application needs beyond specific job ads.</Text></HStack>
              <HStack><Icon as={FaCheckCircle} color={accent} /><Text>Showcase the full breadth of your experience.</Text></HStack>
            </VStack>
          </VStack>
        </SimpleGrid>
      </Box>

      {/* 5. How It Works */}
      <Box id="how-it-works" py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }} bg="brand.50">
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">Get Your Perfect Application in 3 Simple Steps</Heading>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={{ base: 6, md: 10 }}>
          <VStack align="center" spacing={4}>
            <Icon as={FaBrain} boxSize={12} color={accent} />
            <Heading as="h4" size="md" color="navy">Feed Your Arc™</Heading>
            <Text color="slate">Securely upload your existing CVs or manually add your career details. Our AI intelligently populates your personal Career Arc™.</Text>
          </VStack>
          <VStack align="center" spacing={4}>
            <Icon as={FaUserTie} boxSize={12} color={accent} />
            <Heading as="h4" size="md" color="navy">Target Your Role</Heading>
            <Text color="slate">Find a job you love? Simply paste the job description into CandidateV.</Text>
          </VStack>
          <VStack align="center" spacing={4}>
            <Icon as={FaMagic} boxSize={12} color={accent} />
            <Heading as="h4" size="md" color="navy">Apply with Confidence</Heading>
            <Text color="slate">Instantly generate a tailored CV and cover letter, optimized for the role. Download and apply!</Text>
          </VStack>
        </SimpleGrid>
      </Box>

      {/* 6. Why Choose CandidateV? */}
      <Box py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }}>
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">The CandidateV Advantage: More Than Just a CV Builder</Heading>
        <SimpleGrid columns={{ base: 1, md: 4 }} spacing={{ base: 6, md: 10 }}>
          <VStack align="center" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaBrain} boxSize={10} color={accent} />
            <Heading as="h4" size="md" color="navy">Intelligent Personalization</Heading>
            <Text color="slate">Go beyond templates. CandidateV uses your unique Career Arc™ to create genuinely bespoke applications that reflect your true value.</Text>
          </VStack>
          <VStack align="center" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaClock} boxSize={10} color={accent} />
            <Heading as="h4" size="md" color="navy">Radical Time Savings</Heading>
            <Text color="slate">Cut down application time from hours to mere minutes. Apply to more opportunities with less effort.</Text>
          </VStack>
          <VStack align="center" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaTree} boxSize={10} color={accent} />
            <Heading as="h4" size="md" color="navy">Career Long Companion</Heading>
            <Text color="slate">Your Career Arc™ evolves with you, making each future application stronger and smarter. It's an investment in your career journey.</Text>
          </VStack>
          <VStack align="center" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
            <Icon as={FaLock} boxSize={10} color={accent} />
            <Heading as="h4" size="md" color="navy">Your Data, Your Control</Heading>
            <Text color="slate">We prioritize your privacy. Your Career Arc™ is your secure, personal career database. We don't store your uploaded CV files.</Text>
          </VStack>
        </SimpleGrid>
      </Box>

      {/* 7. Testimonials / User Reviews */}
      <Box py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }} bg="white">
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">Don't Just Take Our Word For It...</Heading>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={{ base: 6, md: 10 }}>
          {testimonials.map((t, i) => (
            <VStack key={i} align="center" spacing={4} bg={cardBg} p={6} borderRadius="md" boxShadow="md">
              <HStack>
                {[...Array(t.rating)].map((_, j) => <Icon as={FaStar} key={j} color="warning" />)}
              </HStack>
              <Text fontStyle="italic" color="slate">"{t.quote}"</Text>
              <Avatar name={t.name} src={t.avatar} />
              <Text fontWeight="bold" color="navy">{t.name}</Text>
              <Text fontSize="sm" color="slate">{t.role}</Text>
            </VStack>
          ))}
        </SimpleGrid>
      </Box>

      {/* 8. Pricing Section */}
      <Box id="pricing" py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }}>
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">Find the Perfect Plan to Launch Your Next Career Move</Heading>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={{ base: 6, md: 10 }}>
          {plans.map((plan, i) => (
            <VStack key={i} align="center" spacing={4} bg={plan.highlight ? 'brand.50' : cardBg} p={8} borderRadius="md" boxShadow={plan.highlight ? 'lg' : 'md'} border={plan.highlight ? '2px solid' : undefined} borderColor={plan.highlight ? 'brand.400' : undefined}>
              <Heading as="h3" size="md" color="navy">{plan.name}</Heading>
              <Text fontSize="2xl" fontWeight="bold" color="brand.500">{plan.price}</Text>
              <VStack align="start" spacing={1}>
                {plan.features.map((f, j) => (
                  <HStack key={j}><Icon as={FaCheckCircle} color={accent} /><Text>{f}</Text></HStack>
                ))}
              </VStack>
              <Button colorScheme="brand" variant="solid" size="lg" borderRadius="md">Get Started with {plan.name}</Button>
            </VStack>
          ))}
        </SimpleGrid>
        <Text fontSize="sm" color="text.placeholder" mt={4} textAlign="center">All plans start with a 7-day free trial. Cancel anytime.</Text>
      </Box>

      {/* 9. FAQ Section */}
      <Box py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }} bg="brand.50">
        <Heading as="h2" textStyle="h2" fontSize={{ base: '2xl', md: '4xl' }} mb={12} textAlign="center" color="navy">Frequently Asked Questions</Heading>
        <Accordion allowToggle maxW="3xl" mx="auto">
          {faqs.map((faq, i) => (
            <AccordionItem key={i} borderRadius="md" borderColor="brand.100">
              <AccordionButton _expanded={{ bg: 'brand.50' }}>
                <Box flex="1" textAlign="left" color="navy">{faq.q}</Box>
                <AccordionIcon color="brand.400" />
              </AccordionButton>
              <AccordionPanel pb={4} color="slate">{faq.a}</AccordionPanel>
            </AccordionItem>
          ))}
        </Accordion>
      </Box>

      {/* 10. Final CTA Section */}
      <Box py={{ base: 8, md: 16 }} px={{ base: 2, sm: 4, md: 16 }} bgGradient="linear(to-r, brand.400, brand.600)">
        <VStack spacing={6} align="center" color="white">
          <Heading as="h2" textStyle="h1" fontSize={{ base: '2xl', md: '4xl' }}>Ready to Transform Your Job Search?</Heading>
          <Text fontSize={{ base: 'md', md: 'xl' }}>Stop letting tedious applications hold you back. Join CandidateV today and start applying smarter, faster, and with more confidence.</Text>
          <Button size={{ base: 'md', md: 'lg' }} colorScheme="whiteAlpha" bg="white" color="brand.600" _hover={{ bg: 'brand.50' }} px={10} py={6} fontSize={{ base: 'md', md: 'xl' }} borderRadius="md">Sign Up for Your Free Trial Now</Button>
          <Text fontSize={{ base: 'xs', md: 'sm' }}>No credit card required for trial. Takes less than 2 minutes to get started.</Text>
        </VStack>
      </Box>

      {/* 11. Footer */}
      <Box as="footer" py={8} px={{ base: 2, sm: 4, md: 16 }} bg={cardBg}>
        <Flex direction={{ base: 'column', md: 'row' }} justify="space-between" align="center" gap={4}>
          <HStack spacing={6}>
            <Link href="#" color="brand.500">About Us</Link>
            <Link href="#" color="brand.500">Contact</Link>
            <Link href="#" color="brand.500">Privacy Policy</Link>
            <Link href="#" color="brand.500">Terms of Service</Link>
            <Link href="#" color="brand.500">Blog</Link>
          </HStack>
          <HStack spacing={4}>
            <Icon as={FaRocket} color="brand.400" />
            <Icon as={FaBrain} color="brand.400" />
            <Icon as={FaUserShield} color="brand.400" />
          </HStack>
          <Text fontSize="sm" color="slate">© {new Date().getFullYear()} CandidateV. All Rights Reserved.</Text>
        </Flex>
      </Box>
    </Box>
  );
};

export default HighConvertingLanding; 